import { db } from './src/db.js';
import { config } from './src/config.js';
console.log('🚀 开始执行数据补充脚本...');
console.log('📦 数据库:', config.db.host + ':' + config.db.port + '/' + config.db.database, '\n');
async function count(t){const r=await db.prepare('SELECT COUNT(*) AS c FROM '+t).get();return r?.c||0;}
async function getCatId(t,n){const r=await db.prepare('SELECT id FROM '+t+' WHERE name = ?').get(n);return r?.id;}
function pda(n){return new Date(Date.now()-n*86400000).toISOString().slice(0,19).replace('T',' ');}
async function run(){try{
// 1. 新闻资讯
{const cur=await count('articles');const tg=10;if(cur<tg){console.log('📰 新闻资讯现有',cur,'条，补充',tg-cur,'条...');const st=db.prepare('INSERT INTO articles (category,title,cover,summary,content,tags,author,is_top,status,publish_time) VALUES (?,?,?,?,?,?,?,?,1,?)');const md=[
{c:'company',t:'驰耀科技受邀参加2024南亚东南亚数字经济博览会',s:'公司携最新物联网平台与智慧化解决方案亮相展会。',a:'[\"企业动态\",\"展会合作\"]',u:'市场部',top:0,content:'2024南亚东南亚数字经济博览会于昆明滇池国际会展中心举办。云南驰耀科技作为省内物联网领域重点企业受邀参展，展示了驰耀物联云平台V3.0、智慧园区解决方案等核心产品与方案。展会期间累计接待参观人次超3000人，与20余家企业达成初步合作意向。'},
{c:'news',t:'工信部印发物联网新型基础设施建设三年行动计划',s:'国家层面政策持续加码，物联网产业迎来新机遇。',a:'[\"行业资讯\",\"政策解读\"]',u:'市场部',top:0,content:'工业和信息化部印发《物联网新型基础设施建设三年行动计划（2024-2026年）》，明确到2026年推动物联网技术与经济社会各领域深度融合，物联网连接数突破20亿。聚焦感知终端部署、网络建设、平台培育、应用推广等重点环节。'},
{c:'tech',t:'MQTT 5.0 协议在物联网场景中的应用实践',s:'深入解析MQTT 5.0新特性及高并发接入优化策略。',a:'[\"技术分享\",\"MQTT\",\"物联网协议\"]',u:'技术中心',top:0,content:'MQTT 5.0带来重要改进：会话消息过期机制、请求/响应模式支持、用户属性扩展、共享订阅支持。高并发优化：合理设置KeepAlive参数、Topic分层设计、配合QoS等级进行消息可靠性权衡。'},
{c:'company',t:'驰耀物联云平台通过国家信息安全等级保护三级测评',s:'平台安全能力获得权威认证。',a:'[\"企业动态\",\"资质认证\"]',u:'行政部',top:0,content:'驰耀物联云平台顺利通过国家信息安全等级保护三级测评。等保三级是国家对非银行机构信息系统的最高安全等级要求，覆盖物理安全、网络安全、主机安全、应用安全、数据安全等多个层面。'},
{c:'news',t:'AI+物联网：边缘智能成为产业升级新引擎',s:'人工智能与物联网深度融合催生边缘智能新范式。',a:'[\"行业资讯\",\"技术趋势\"]',u:'市场部',top:0,content:'随着AI算力成本持续下降与边缘计算硬件成熟，边缘智能将AI推理能力部署在靠近数据源的边缘节点，实现数据本地化处理与实时决策。在安防、工业、农业等领域应用前景广阔。'},
{c:'tech',t:'基于WebRTC的低延迟视频监控直播方案实践',s:'浏览器端实现秒级延迟的监控视频直播方案。',a:'[\"技术分享\",\"视频监控\",\"WebRTC\"]',u:'技术中心',top:0,content:'基于WebRTC的低延迟直播方案可实现浏览器端500ms以内延迟。架构：IPC通过RTSP输出→媒体网关转换为WebRTC→浏览器播放。关键技术：NACK+PLI丢包重传、Jitter Buffer抖动缓冲、动态码率自适应。'},
{c:'company',t:'驰耀科技荣获云南省2024年度专精特新中小企业认定',s:'公司凭借专业化能力与创新成果获得省级认定。',a:'[\"企业动态\",\"荣誉资质\"]',u:'行政部',top:1,content:'云南省工信厅公布2024年度专精特新中小企业名单，云南驰耀科技凭借在物联网平台与智慧化解决方案领域的专业化能力、精细化管理与创新成果成功入选。'},
{c:'news',t:'智慧园区市场规模预计2027年突破8000亿元',s:'数字化转型加速推动智慧园区建设热潮。',a:'[\"行业资讯\",\"市场分析\"]',u:'市场部',top:0,content:'据行业报告，中国智慧园区市场规模预计2027年突破8000亿元，复合年增长率约15.6%。建设正从基础设施部署迈向深度应用与运营优化阶段，智慧安防、能耗、通行等细分领域需求旺盛。'},
{c:'tech',t:'时序数据库InfluxDB在物联网数据存储中的最佳实践',s:'从模型设计、写入优化、查询性能等方面分享实战经验。',a:'[\"技术分享\",\"时序数据库\",\"性能优化\"]',u:'技术中心',top:0,content:'InfluxDB最佳实践：1) 数据模型：高基数维度放tag、数值放field，避免序列爆炸。2) 写入优化：批量写入5000-10000点、开启Gzip压缩。3) 查询性能：时间范围尽可能小、善用Continuous Query预聚合。'},
{c:'company',t:'驰耀科技与云南某职业学院达成产教融合战略合作',s:'校企共建物联网实训基地。',a:'[\"企业动态\",\"产教融合\"]',u:'人力资源部',top:0,content:'驰耀科技与云南某职业学院签署产教融合战略合作协议，双方将在物联网专业建设、实训基地共建、师资培养、学生实习就业等方面开展深度合作。公司捐赠价值百万元的实训设备与平台授权。'}
];const nd=tg-cur;for(let i=0;i<nd&&i<md.length;i++){const x=md[i];await st.run(x.c,x.t,'',x.s,x.content,x.a,x.u,x.top,pda(i+1));console.log('  +',x.t.slice(0,30)+'...');}}else console.log('📰 新闻资讯现有',cur,'条，已达标。');}
// 2. 产品中心
{const cur=await count('products');const tg=10;if(cur<tg){console.log('\n💼 产品中心现有',cur,'条，补充',tg-cur,'条...');const cat={'物联网平台':await getCatId('product_categories','物联网平台'),'安防监控设备':await getCatId('product_categories','安防监控设备'),'智慧硬件终端':await getCatId('product_categories','智慧硬件终端'),'系统集成服务':await getCatId('product_categories','系统集成服务')};const st=db.prepare('INSERT INTO products (category_id,name,model,cover,images,intro,detail,params,docs,status,sort,seo_title) VALUES (?,?,?,?,?,?,?,?,?,1,?,?)');const md=[
{cn:'物联网平台',name:'驰耀设备管理平台',model:'CY-DMP V2.1',sort:7,intro:'专注设备全生命周期管理的专业平台，覆盖设备档案、运维工单、远程诊断。',detail:'驰耀设备管理平台提供设备入库、出库、安装、运行、维护、报废的全生命周期管理。集成物联网接入能力，实时获取设备运行数据，与工单系统联动实现故障自动派单与维保提醒。',params:'[["设备档案","完整台账管理"],["工单管理","自动派单/进度跟踪"],["远程诊断","远程参数配置/日志采集"],["维保提醒","自动维保计划"]]'},
{cn:'安防监控设备',name:'200万像素电梯专用智能摄像机',model:'CY-IPC200-Elevator',sort:8,intro:'电梯场景专用摄像机，支持电动车识别、摔倒检测、滞留检测等AI功能。',detail:'针对电梯场景专门设计，采用广角畸变校正镜头与抗干扰设计，内置电动车识别、人员摔倒检测、滞留检测、电瓶车入梯报警等专属AI算法，配合电梯楼层显示叠加。',params:'[["像素","200万 1080P"],["视场角","水平150°广角畸变校正"],["AI功能","电动车/摔倒/滞留检测"],["楼层叠加","支持楼层显示OSD"]]'},
{cn:'智慧硬件终端',name:'无线环境监测传感终端',model:'CY-ENV-THPM',sort:9,intro:'LoRaWAN/NB-IoT无线终端，一体化监测温湿度、PM2.5、CO2等环境参数。',detail:'集成高精度温湿度、PM2.5/PM10、CO2、TVOC、光照等传感器，支持LoRaWAN或NB-IoT无线传输，内置电池续航可达3年。适用于机房、仓库、办公区、农业大棚等场景。',params:'[["监测参数","温湿度/PM2.5/CO2/TVOC/光照"],["无线传输","LoRaWAN / NB-IoT"],["续航","内置电池 3 年"],["防护等级","IP65"]]'},
{cn:'智慧硬件终端',name:'智能人脸门禁考勤一体机',model:'CY-AC-Face5',sort:10,intro:'5英寸触摸屏人脸门禁考勤机，支持活体检测、NFC卡、密码多种验证方式。',detail:'采用5英寸高清触摸屏，配备活体检测双目摄像头，支持3000人脸库、1秒快速识别。支持NFC刷卡、密码、二维码开门，内置考勤功能可自定义排班规则。',params:'[["屏幕","5寸 IPS 触摸屏"],["人脸库","3000张活体检测"],["识别速度","<1秒"],["验证方式","人脸/NFC/密码/二维码"]]'}
];const nd=tg-cur;for(let i=0;i<nd&&i<md.length;i++){const p=md[i];await st.run(cat[p.cn],p.name,p.model,'','[]',p.intro,p.detail,p.params,'[]',p.sort,p.name);console.log('  +',p.name);}}else console.log('\n💼 产品中心现有',cur,'条，已达标。');}
// 3. 解决方案
{const cur=await count('solutions');const tg=10;if(cur<tg){console.log('\n💡 解决方案现有',cur,'条，补充',tg-cur,'条...');const st=db.prepare('INSERT INTO solutions (name,industry,cover,images,intro,detail,scenario,architecture,value_points,related_products,related_cases,status,sort,seo_title) VALUES (?,?,?,?,?,?,?,?,?,?,?,1,?,?)');const md=[
{name:'智慧农业物联网解决方案',industry:'智慧农业',sort:4,intro:'面向设施农业、大田种植、畜禽养殖的物联网方案，实现精准种植。',detail:'通过部署环境传感器、视频监控、智能灌溉设备，结合驰耀物联云平台，提供环境监测、智能灌溉、病虫害预警、长势分析、溯源管理等能力。',scenario:'适用于温室大棚、花卉种植、果园、畜禽养殖场、水产养殖等场景。',arch:'感知层（传感器+摄像头）→ 传输层（LoRaWAN/NB-IoT/4G）→ 平台层（驰耀物联云+AI分析）→ 应用层',values:'["节水节肥 30%+","人工巡检降低 60%","病虫害发现提前 5-7 天","亩均产量提升 15-25%"]'},
{name:'智慧仓储物流解决方案',industry:'智慧物流',sort:5,intro:'面向仓储与物流园区的智能化方案，涵盖视频监控、车辆调度等。',detail:'围绕仓储安全、作业效率、货物管理三大诉求，部署AI视频监控、智能门禁、车辆识别、电子围栏、货物感知等设施，实现24小时智能值守。',scenario:'适用于电商仓库、冷链仓储、物流园区、港口码头等场景。',arch:'AI摄像机+道闸+门禁+传感 → 边缘网关 → 驰耀物联云仓储模块 → 运营大屏',values:'["偷盗损失降低 80%+","车辆过闸效率提升 4倍","人工巡逻减少 90%","库存准确率 99.5%"]'},
{name:'智慧医院安防与后勤解决方案',industry:'智慧医疗',sort:6,intro:'面向医院的安防与后勤综合方案，保障医患安全、提升管理效率。',detail:'针对医院人流量大、人员复杂特点，构建视频监控AI分析、人脸识别、门禁分级授权、一键报警、婴儿防盗、能耗管理、保洁巡检等功能模块。',scenario:'适用于综合医院、专科医院、社区卫生院等医疗场景。',arch:'前端感知 → 智能分析平台 → 安防综合管理平台 → 保卫处/后勤中心 + 移动端',values:'["重点区域无死角覆盖","纠纷告警提前 30秒","后勤能耗降低 25%","安保响应 <1 分钟"]'},
{name:'智慧能源管理与能耗监测方案',industry:'智慧能源',sort:7,intro:'面向企业、园区、公共建筑的能耗精细管理方案，节能效果可量化。',detail:'对电、水、燃气、蒸汽等能源分项分区计量采集，构建企业级能源管理中心，结合分析模型自动识别浪费点，输出节能建议，配合智能控制策略实现自动节能。',scenario:'适用于工厂、医院、学校、写字楼、商业综合体、政府机构等场景。',arch:'智能电表/水表/气表 → 边缘采集网关 → 能源管理平台 → 能耗大屏 + 报表',values:'["能耗精度达 98%+","节能空间自动识别","综合节能率 10-25%","投资回收 1-2 年"]'},
{name:'智慧工地安全监管解决方案',industry:'智慧工地',sort:8,intro:'面向建筑施工工地的安全监管方案，实现人员、机械、环境全方位管理。',detail:'集成实名制人员通道、AI视频安全识别、扬尘噪声监测、塔机安全监测、车辆清洗识别等子系统，通过工地监管平台实现数据统一汇聚与联动处置。',scenario:'适用于房屋建筑、市政工程、交通基建等各类施工工地。',arch:'闸机/AI摄像机/环境监测仪/塔机黑匣子 → 边缘机柜 → 智慧工地监管平台',values:'["实名制考勤率 100%","未戴安全帽识别 95%+","扬尘超标自动喷淋","事故率下降 60%+"]'},
{name:'智慧社区与老旧小区改造方案',industry:'智慧社区',sort:9,intro:'助力老旧小区改造升级，提供智慧安防、门禁、停车、便民服务能力。',detail:'针对小区安防薄弱、出入不便、停车混乱、服务缺失等痛点，低成本实现智能化升级。包含人脸门禁、视频监控、车辆识别、快递柜、公告发布、便民缴费等模块。',scenario:'适用于城市老旧小区、新建商品房小区、保障房社区等场景。',arch:'人脸门禁+道闸+摄像机+快递柜 → 社区网关 → 社区管理云平台 → 物业/居民小程序',values:'["改造成本降低 40%","盗窃案件下降 70%+","居民通行便捷度提升","满意度提升 30%+"]'},
{name:'智慧公厕与环境卫生监管方案',industry:'智慧城市',sort:10,intro:'面向城市公厕、环卫设施的智慧化监管方案，提升公共服务水平。',detail:'在公厕部署人体存在、空气质量、异味、水电、厕纸余量等传感器，结合客流统计，实现使用状态监测、异味超标排风、耗材不足提醒、保洁打卡等功能。',scenario:'适用于城市核心区、旅游景区、交通枢纽公厕及道路环卫管理场景。',arch:'各类环境与客流传感器 → LoRa/NB-IoT → 环卫监管云平台 → 大屏+保洁APP',values:'["异味投诉减少 80%+","保洁效率提升 3倍","耗材浪费减少 50%","市民满意度显著提升"]'}
];const nd=tg-cur;for(let i=0;i<nd&&i<md.length;i++){const s=md[i];await st.run(s.name,s.industry,'','[]',s.intro,s.detail,s.scenario,s.arch,s.values,'[]','[]',s.sort,s.name);console.log('  +',s.name);}}else console.log('\n💡 解决方案现有',cur,'条，已达标。');}
// 4. 案例展示
{const cur=await count('cases');const tg=10;if(cur<tg){console.log('\n🏆 案例展示现有',cur,'条，补充',tg-cur,'条...');const cat={'智慧园区':await getCatId('case_categories','智慧园区'),'智慧教育':await getCatId('case_categories','智慧教育'),'智慧安防':await getCatId('case_categories','智慧安防'),'企业数字化':await getCatId('case_categories','企业数字化')};const st=db.prepare('INSERT INTO cases (category_id,name,cover,images,intro,detail,tags,results,related_products,related_solutions,status,sort,seo_title) VALUES (?,?,?,?,?,?,?,?,?,?,1,?,?)');const md=[
{cn:'智慧园区',sort:4,name:'曲靖某智慧物流园区监控与车辆管理系统项目',intro:'为大型物流园区建设车辆识别、视频监控、周界防范一体化系统。',detail:'为占地500亩的物流园区建设智慧化系统，包含出入口道闸与车牌识别、视频监控AI分析、周界防范、仓库智能值守等子系统。通过驰耀物联云平台实现数据联动。',tags:'["智慧园区","物流仓储","车辆识别"]',results:'[["500+","监控点位覆盖"],["4","进出入大门"],["10秒内","车辆过闸放行"],["99.8%","车牌识别准确率"]]'},
{cn:'智慧教育',sort:5,name:'昆明某中学智慧校园安防与一卡通项目',intro:'为中学建设安防监控、人脸门禁、校园一卡通、访客管理系统。',detail:'部署智能摄像机300余路、校门与宿舍楼人脸门禁，实现学生刷脸进出与考勤。一卡通覆盖食堂、图书馆、热水等场景，访客系统实现线上预约与自动授权。',tags:'["智慧教育","一卡通","人脸门禁"]',results:'[["300+","监控点位"],["6","栋宿舍人脸门禁"],["1","卡通覆盖全场景"],["50%","安保人力节省"]]'},
{cn:'企业数字化',sort:6,name:'玉溪某卷烟辅料企业能源管理与设备联网项目',intro:'部署能源管理系统与生产设备联网，实现能耗精细化管理。',detail:'对配电、水、压缩空气系统分项计量改造，采集38台主要设备运行数据，建设能源与设备监控平台。通过数据分析发现多处压缩空气泄漏与设备空载浪费，节能改造后收益明显。',tags:'["智能制造","能源管理","设备联网"]',results:'[["38","台设备联网监控"],["126","个能耗计量点"],["18%","综合能耗下降"],["8个月","投资回收周期"]]'},
{cn:'智慧安防',sort:7,name:'大理某旅游景区智慧安防与客流管控系统',intro:'为5A级景区建设视频监控、客流统计、应急广播、一键求助系统。',detail:'覆盖景区20余平方公里，部署高清摄像机280余路、客流统计20处、应急广播与一键求助60余个。支持实时客流热力图、人员密度预警、应急事件一键联动广播。',tags:'["智慧安防","旅游景区","客流管控"]',results:'[["280+","路摄像机"],["60+","一键求助柱"],["<2分钟","应急响应时间"],["0","重大安全事故"]]'},
{cn:'智慧园区',sort:8,name:'楚雄某政务服务中心智能化系统集成项目',intro:'为政务大楼提供综合布线、网络、安防、信息发布、会议系统集成服务。',detail:'涵盖综合布线、计算机网络、视频监控与门禁、排队叫号与信息发布、多功能会议室、机房工程等10余个智能化子系统的深化设计与施工实施。项目按期高质量交付。',tags:'["系统集成","政务服务","信息化建设"]',results:'[["12","个智能化子系统"],["8","层办公大楼覆盖"],["98%","一次性验收通过率"],["优","工程质量评定"]]'},
{cn:'企业数字化',sort:9,name:'红河州某农业科技公司智慧农业大棚物联网项目',intro:'为高端花卉种植企业部署环境监测与智能灌溉控制系统。',detail:'在12栋温室大棚内部署温湿度、光照、土壤水分、CO2等传感终端，配套智能电磁阀与卷膜/通风设备控制，通过驰耀物联云平台实现环境数据查看与灌溉通风的自动/远程控制。',tags:'["智慧农业","物联网","精准种植"]',results:'[["12","栋温室大棚覆盖"],["人工巡检减少","80%"],["灌溉用水节约","35%"],["A级花率提升","22%"]]'},
{cn:'智慧安防',sort:10,name:'昭通某县城区智慧安防雪亮工程增补项目',intro:'为区县雪亮工程增补AI智能分析与视频结构化能力。',detail:'为已建的500余路摄像机系统增加AI智能分析能力，通过智能分析服务器实现人脸抓拍比对、车辆结构化识别、重点区域行为分析等功能，与公安大数据平台对接。',tags:'["智慧安防","雪亮工程","AI视频分析"]',results:'[["500+","路接入分析"],["协助破案","数十起"],["重点人员预警","实时推送"],["防控能力","显著提升"]]'}
];const nd=tg-cur;for(let i=0;i<nd&&i<md.length;i++){const c=md[i];await st.run(cat[c.cn],c.name,'','[]',c.intro,c.detail,c.tags,c.results,'[]','[]',c.sort,c.name);console.log('  +',c.name.slice(0,30)+'...');}}else console.log('\n🏆 案例展示现有',cur,'条，已达标。');}
// 5. 软件资料
{const cur=await count('downloads');const tg=10;if(cur<tg){console.log('\n📚 软件资料现有',cur,'条，补充',tg-cur,'条...');const cat={'驱动程序':await getCatId('download_categories','驱动程序'),'固件升级':await getCatId('download_categories','固件升级'),'使用手册':await getCatId('download_categories','使用手册'),'SDK 开发包':await getCatId('download_categories','SDK 开发包'),'技术文档':await getCatId('download_categories','技术文档')};const st=db.prepare('INSERT INTO downloads (category_id,name,icon,intro,detail,version,files,size,update_log,system_require,related_products,status,sort,seo_title) VALUES (?,?,?,?,?,?,?,?,?,?,?,1,?,?)');const md=[
{cn:'技术文档',sort:7,name:'驰耀开放平台 API 接口文档',icon:'api',intro:'驰耀物联云开放平台完整 REST API 接口文档，供第三方系统对接使用。',detail:'详细介绍所有对外 REST API 接口，包括设备管理、数据查询、命令下发、告警、组织与用户管理等接口，附带请求示例与返回字段说明。',version:'V3.0',files:'[["驰耀开放平台API文档V3.0.pdf","PDF","8.6MB"]]',size:'8.6MB',update:'2024-12-05 更新：新增批量命令下发与历史数据聚合查询接口',require:'开发者需先在平台申请 API Key，支持 HTTP/HTTPS 调用'},
{cn:'SDK 开发包',sort:8,name:'Android 移动端 SDK 开发包',icon:'code',intro:'Android 平台 SDK，便于移动端 App 快速集成物联网平台能力。',detail:'提供用户登录、设备列表、实时数据订阅、命令下发、告警推送等功能封装。采用Kotlin编写，兼容Java调用，附带完整Demo工程。',version:'V1.4.0',files:'[["chiyao-iot-sdk-android-v1.4.0.zip","ZIP","6.2MB"]]',size:'6.2MB',update:'2024-11-28 发布：新增 WebSocket 实时数据推送，修复已知问题',require:'Android 6.0+ (API Level 23+)，推荐使用 Android Studio'},
{cn:'使用手册',sort:9,name:'边缘计算智能网关配置手册',icon:'doc',intro:'CY-EG200 边缘计算网关用户配置手册，含接线、参数配置、协议对接。',detail:'详细介绍CY-EG200系列网关的硬件接口、上电启动、本地Web配置、平台接入流程、200+工业协议配置、断网续传、固件升级等内容，是实施工程师必备资料。',version:'V2.1',files:'[["CY-EG200边缘计算网关配置手册V2.1.pdf","PDF","15.3MB"]]',size:'15.3MB',update:'2024-10-25 更新：新增西门子S7协议与BACnet协议配置章节',require:'适用于 CY-EG200 V2.x 硬件版本，建议使用 Chrome 浏览器'},
{cn:'固件升级',sort:10,name:'网络摄像机 IPC 固件升级包 V5.6.13',icon:'chip',intro:'CY-IPC200/CY-IPC400 系列智能网络摄像机最新固件升级包。',detail:'针对CY-IPC200/400系列摄像机，修复已知问题并优化算法性能。升级前确保接入稳定网络并保持供电，过程约3-5分钟，期间请勿断电。',version:'V5.6.13',files:'[["IPC_CY-IPC200-400_V5.6.13.dav","DAV","34.8MB"]]',size:'34.8MB',update:'修复：1)夜视切换异常；2)优化人脸识别精度；3)增加ONVIF Profile T；4)定时重启偶发失效',require:'适用于 CY-IPC200 / CY-IPC400 系列机型，升级前版本需 ≥ V5.3.00'}
];const nd=tg-cur;for(let i=0;i<nd&&i<md.length;i++){const d=md[i];await st.run(cat[d.cn],d.name,d.icon,d.intro,d.detail,d.version,d.files,d.size,d.update,d.require,'[]',d.sort,d.name);console.log('  +',d.name.slice(0,30)+'...');}}else console.log('\n📚 软件资料现有',cur,'条，已达标。');}
console.log('\n'+('='.repeat(50)));
console.log('✅ 数据补充完成！最终统计：');
console.log('='.repeat(50));
for(const [l,t] of [['📰 新闻资讯（互联查询）','articles'],['💼 产品中心','products'],['💡 解决方案','solutions'],['🏆 案例展示','cases'],['📚 软件资料','downloads']]){const n=await count(t);console.log('   ',(n>=10?'✅ ':'⚠️ '),l.padEnd(22),':',n,'条');}
console.log('='.repeat(50));process.exit(0);
}catch(e){console.error('\n❌ 执行出错：',e.message);console.error(e.stack);process.exit(1);}}
run();
